name: Hello World Action

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: Make API Call
        run: |
          curl https://jsonplaceholder.typicode.com/todos/1
          echo "API call completed"
  hello-william:
    steps:
      - name: Print Hello william
        run: echo "William is back!"
      